import {
  Cpu, ShoppingBag, Activity, Home, TrendingUp, Briefcase,
  Zap, Server, Shield, ShieldCheck, Factory, Truck, CreditCard, Cloud, FlaskConical,
  HeartPulse, Heart, Landmark, Scale, Building2, Building, HardHat, Sun, Car, Hotel,
  Wrench, Store, Users, GraduationCap, Plane, Utensils, ShoppingCart, Stethoscope, Pill,
  Leaf, Fuel, Ship, Package, Hammer, Laptop, Smartphone, Camera, Gamepad2, Dumbbell,
  Scissors, Shirt, Gem, Banknote, Globe, Lock, Rocket, Droplets, Flame, Wifi, Database,
  Code, Megaphone, Newspaper, BookOpen, Baby, PawPrint, Tractor, Warehouse, Mountain,
  Palette, Handshake, Gavel, Syringe, Bed, Coffee, Recycle, Bike,
  type LucideIcon,
} from 'lucide-react'

export interface IndustryIconOption { value: string; label: string; icon: LucideIcon }

// The first six keys are what existing rows already store — don't rename them.
// The rest cover the industries the client actually sells to (energy, data
// centres, cybersecurity, manufacturing, logistics, biotech, legal, …) so the
// picker isn't limited to a handful of generic icons.
export const INDUSTRY_ICONS: IndustryIconOption[] = [
  { value: 'cpu', label: 'SaaS & Tech', icon: Cpu },
  { value: 'shopping-bag', label: 'E-Commerce & Retail', icon: ShoppingBag },
  { value: 'activity', label: 'Healthcare & Medical', icon: Activity },
  { value: 'home', label: 'Real Estate & Property', icon: Home },
  { value: 'trending-up', label: 'Finance & FinTech', icon: TrendingUp },
  { value: 'briefcase', label: 'Professional Services', icon: Briefcase },
  { value: 'zap', label: 'Energy & Utilities', icon: Zap },
  { value: 'server', label: 'Data Centers', icon: Server },
  { value: 'shield', label: 'Security', icon: Shield },
  { value: 'shield-check', label: 'Cybersecurity & Compliance', icon: ShieldCheck },
  { value: 'factory', label: 'Manufacturing', icon: Factory },
  { value: 'truck', label: 'Logistics & Freight', icon: Truck },
  { value: 'credit-card', label: 'Payments', icon: CreditCard },
  { value: 'cloud', label: 'B2B SaaS & Cloud', icon: Cloud },
  { value: 'flask-conical', label: 'Biotech & Labs', icon: FlaskConical },
  { value: 'heart-pulse', label: 'Clinics & Care', icon: HeartPulse },
  { value: 'heart', label: 'Healthcare', icon: Heart },
  { value: 'stethoscope', label: 'Medical Practice', icon: Stethoscope },
  { value: 'pill', label: 'Pharma', icon: Pill },
  { value: 'syringe', label: 'Dental & Clinics', icon: Syringe },
  { value: 'landmark', label: 'Banking & Government', icon: Landmark },
  { value: 'banknote', label: 'Lending & Insurance', icon: Banknote },
  { value: 'scale', label: 'Legal', icon: Scale },
  { value: 'gavel', label: 'Law Firms', icon: Gavel },
  { value: 'building-2', label: 'Commercial Property', icon: Building2 },
  { value: 'building', label: 'Corporate', icon: Building },
  { value: 'hard-hat', label: 'Construction', icon: HardHat },
  { value: 'hammer', label: 'Trades & Contractors', icon: Hammer },
  { value: 'wrench', label: 'Home Services', icon: Wrench },
  { value: 'sun', label: 'Solar & Renewables', icon: Sun },
  { value: 'flame', label: 'Oil & Gas', icon: Flame },
  { value: 'fuel', label: 'Fuel & Petroleum', icon: Fuel },
  { value: 'droplets', label: 'Water', icon: Droplets },
  { value: 'leaf', label: 'Agriculture & Green', icon: Leaf },
  { value: 'recycle', label: 'Sustainability', icon: Recycle },
  { value: 'tractor', label: 'Farming', icon: Tractor },
  { value: 'car', label: 'Automotive', icon: Car },
  { value: 'bike', label: 'Powersports', icon: Bike },
  { value: 'plane', label: 'Aviation & Travel', icon: Plane },
  { value: 'ship', label: 'Marine & Shipping', icon: Ship },
  { value: 'hotel', label: 'Hospitality', icon: Hotel },
  { value: 'bed', label: 'Hotels & Stays', icon: Bed },
  { value: 'utensils', label: 'Restaurants', icon: Utensils },
  { value: 'coffee', label: 'Cafes & Food', icon: Coffee },
  { value: 'store', label: 'Franchise & Retail Stores', icon: Store },
  { value: 'shopping-cart', label: 'Online Shopping', icon: ShoppingCart },
  { value: 'shirt', label: 'Fashion & Apparel', icon: Shirt },
  { value: 'gem', label: 'Luxury & Jewelry', icon: Gem },
  { value: 'scissors', label: 'Beauty & Salons', icon: Scissors },
  { value: 'dumbbell', label: 'Fitness', icon: Dumbbell },
  { value: 'users', label: 'Recruitment & Staffing', icon: Users },
  { value: 'handshake', label: 'Partnerships & B2B', icon: Handshake },
  { value: 'graduation-cap', label: 'Education', icon: GraduationCap },
  { value: 'book-open', label: 'Publishing', icon: BookOpen },
  { value: 'newspaper', label: 'Media & News', icon: Newspaper },
  { value: 'megaphone', label: 'Marketing & Advertising', icon: Megaphone },
  { value: 'camera', label: 'Photography & Video', icon: Camera },
  { value: 'gamepad-2', label: 'Gaming', icon: Gamepad2 },
  { value: 'palette', label: 'Design & Creative', icon: Palette },
  { value: 'laptop', label: 'Software & IT', icon: Laptop },
  { value: 'smartphone', label: 'Mobile Apps', icon: Smartphone },
  { value: 'code', label: 'Development', icon: Code },
  { value: 'database', label: 'Data & Analytics', icon: Database },
  { value: 'wifi', label: 'Telecom', icon: Wifi },
  { value: 'lock', label: 'Privacy & Access', icon: Lock },
  { value: 'rocket', label: 'Startups', icon: Rocket },
  { value: 'globe', label: 'Global & Export', icon: Globe },
  { value: 'warehouse', label: 'Warehousing', icon: Warehouse },
  { value: 'package', label: 'Supply Chain', icon: Package },
  { value: 'mountain', label: 'Outdoor & Adventure', icon: Mountain },
  { value: 'baby', label: 'Childcare', icon: Baby },
  { value: 'paw-print', label: 'Pets & Vet', icon: PawPrint },
]

export const INDUSTRY_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  INDUSTRY_ICONS.map(o => [o.value, o.icon])
)

export const DEFAULT_INDUSTRY_ICON = TrendingUp
